### ISSUE TITLE
Possible issue about the robust value iteration

### ISSUE THREAD

**Issue by DanialTaheri** [eleurent/rl-agents#36]
Hi, 

I was trying to run the experiment file using RVI algorithm. But, I face an error as follows. I appreciate it if you let me know if I am doing sth wrong.
My bash command:
 python3 experiments.py evaluate configs/FiniteMDPEnv/large/env_2.json configs/FiniteMDPEnv/large/agents/value_iteration.json --train

The error:
Traceback (most recent call last):
  File "experiments.py", line 149, in <module>
    main()
  File "experiments.py", line 44, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 60, in evaluate
    env = load_environment(environment_config)
  File "/.local/lib/python3.6/site-packages/rl_agents/agents/common/factory.py", line 69, in load_environment
    __import__(env_config["import_module"])
ModuleNotFoundError: No module named 'finite_mdp'

**Comment by eleurent** [comment]
Hi @DanialTaheri 
Like the value iteration, the robust value iteration requires the knowledge of the MDP(s), described in the form of a `FiniteMDPEnv`, defined in [this project](https://github.com/eleurent/finite-mdp).
(It can also be used on environments that provide a `to_finite_mdp()` method that converts them into a `FiniteMDPEnv`.)

To fix your error, simply clone the project locally, or install it with pip:
`pip install --user git+https://github.com/eleurent/finite-mdp`
