### ISSUE TITLE
analyze agent performances

### ISSUE THREAD

**Issue by denghuifan** [eleurent/rl-agents#63]
**I can't use the analyze.py to monitor the agent performances.
This is my code:**
`!python3 analyze.py run /openaigym.episode_batch.1.3395.stats.json`
**And the error  as following:**
`INFO:root:Fetching data in /openaigym.episode_batch.1.3395.stats.json
INFO:root:Found 0 runs.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'episode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "analyze.py", line 134, in <module>
    main()
  File "analyze.py", line 36, in main
    RunAnalyzer(opts['<run_folder>'], out=opts["--out"], episodes_range=episodes_range)
  File "analyze.py", line 49, in __init__
    self.analyze()
  File "analyze.py", line 100, in analyze
    self.find_best_run()
  File "analyze.py", line 114, in find_best_run
    df = df[df["episode"] == df["episode"].max()].sort_values(criteria, ascending=ascending)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'episode'`
**Could you tell my how to solve it, Thanks a lot.**

**Comment by denghuifan** [comment]
**This is the ...stats.json**
[data.zip](https://github.com/eleurent/rl-agents/files/5939375/data.zip)

**Comment by eleurent** [comment]
Hi @denghuifan,
You should not provide the path to the .stats.json file, but rather that of the directory that contains it.

**Comment by eleurent** [comment]
But also, this script is kind of deprecated: you could rather use Tensorboard to visualize your runs, which is more flexible.

**Comment by denghuifan** [comment]
I will try it, thanks a lot!!
