### ISSUE TITLE
Possible issue about the module named 'rl_agents.agents.tree_search.robust'

### ISSUE THREAD

**Issue by JasonWong815** [eleurent/rl-agents#75]
Hi Edouard,

Thank you for your amazing contributions and ideas. I was trying to run the experiment file. But, I face an error as follows. I'd appreciate it if you could let me know if I'm doing something incorrectly.

My bash **command**:
python experiments.py evaluate configs/HighwayEnv/env_linear.json \
                               configs/HighwayEnv/agents/IntervalRobustPlannerAgent/baseline.json \
                               --test --episodes=1

The **error**:
Traceback (most recent call last):
  File "experiments.py", line 148, in <module>
    main()
  File "experiments.py", line 43, in main
    evaluate(opts['<environment>'], opts['<agent>'], opts)
  File "experiments.py", line 60, in evaluate
    agent = load_agent(agent_config, env)
  File "C:\Users\whj\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 41, in load_agent
    return agent_factory(env, agent_config)
  File "C:\Users\whj\AppData\Roaming\Python\Python37\site-packages\rl_agents\agents\common\factory.py", line 23, in agent_factory
    agent_class = getattr(importlib.import_module(module_name), class_name)
  File "D:\Anaconda3\envs\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'rl_agents.agents.tree_search.robust'**

It seems that there is no file called 'robust' under the path of 'rl_agents\agents\tree_search\'. I would be really grateful if you could assist me with this. 

Jason Wang

**Comment by yuzhouxianzhi** [comment]
Hi，i also face an same error as yours. Do you have done it?

**Comment by eleurent** [comment]
Yes sorry, I have moved the files but did not update the paths in the config. This is now fixed.
